apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: ap-south-1

nodeGroups:
  - name: ng-1
    desiredCapacity: 2
    instanceType: t2.micro
    ssh:
      publicKeyPath: ~/.ssh/my-eks-cluster.pub

